CREATE TABLE IF NOT EXISTS cv_vendor_table_field (
    id BIGINT NOT NULL AUTO_INCREMENT,
    table_group VARCHAR(32) NOT NULL,
    table_code VARCHAR(64) NOT NULL,
    field_key VARCHAR(128) NOT NULL,
    field_label VARCHAR(255) NOT NULL,
    field_type VARCHAR(32) NOT NULL DEFAULT 'text',
    field_precision INT DEFAULT NULL,
    field_width INT DEFAULT NULL,
    field_options TEXT DEFAULT NULL,
    required_flag TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    status CHAR(1) NOT NULL DEFAULT '0',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    remark VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cv_vendor_table_field (table_group, table_code, field_key),
    KEY idx_cv_vendor_table_field_table (table_group, table_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Vendor managed table field definition';
