-- Vendor sample field alignment migration.
-- Database boundary: vendor only.

ALTER TABLE cv_factor_record
    ADD COLUMN factor_table_code VARCHAR(64) NOT NULL DEFAULT '201ef' AFTER version_id,
    ADD COLUMN factor_key VARCHAR(128) DEFAULT NULL AFTER factor_unit,
    ADD COLUMN emission_source_name VARCHAR(255) DEFAULT NULL AFTER factor_key,
    ADD COLUMN emission_source_name_en VARCHAR(255) DEFAULT NULL AFTER emission_source_name,
    ADD COLUMN fuel_material_category VARCHAR(255) DEFAULT NULL AFTER emission_source_name_en,
    ADD COLUMN source_unit VARCHAR(64) DEFAULT NULL AFTER fuel_material_category,
    ADD COLUMN co2 DECIMAL(28, 10) DEFAULT NULL AFTER source_unit,
    ADD COLUMN ch4 DECIMAL(28, 10) DEFAULT NULL AFTER co2,
    ADD COLUMN n2o DECIMAL(28, 10) DEFAULT NULL AFTER ch4,
    ADD COLUMN hfcs DECIMAL(28, 10) DEFAULT NULL AFTER n2o,
    ADD COLUMN pfcs DECIMAL(28, 10) DEFAULT NULL AFTER hfcs,
    ADD COLUMN sf6 DECIMAL(28, 10) DEFAULT NULL AFTER pfcs,
    ADD COLUMN nf3 DECIMAL(28, 10) DEFAULT NULL AFTER sf6,
    ADD COLUMN applicable_scope VARCHAR(255) DEFAULT NULL AFTER nf3,
    ADD COLUMN factor_source VARCHAR(255) DEFAULT NULL AFTER applicable_scope,
    ADD COLUMN gwp_ch4 DECIMAL(28, 10) DEFAULT NULL AFTER factor_source,
    ADD COLUMN gwp_n2o DECIMAL(28, 10) DEFAULT NULL AFTER gwp_ch4,
    ADD COLUMN gwp_hfcs DECIMAL(28, 10) DEFAULT NULL AFTER gwp_n2o,
    ADD COLUMN gwp_pfcs DECIMAL(28, 10) DEFAULT NULL AFTER gwp_hfcs,
    ADD COLUMN gwp_sf6 DECIMAL(28, 10) DEFAULT NULL AFTER gwp_pfcs,
    ADD COLUMN gwp_nf3 DECIMAL(28, 10) DEFAULT NULL AFTER gwp_sf6,
    ADD COLUMN factor_gwp DECIMAL(28, 10) DEFAULT NULL AFTER gwp_nf3,
    ADD COLUMN version_province_code VARCHAR(128) DEFAULT NULL AFTER factor_gwp,
    ADD COLUMN factor_version VARCHAR(64) DEFAULT NULL AFTER version_province_code,
    ADD COLUMN division_code VARCHAR(64) DEFAULT NULL AFTER factor_version,
    ADD COLUMN division_name VARCHAR(255) DEFAULT NULL AFTER division_code,
    ADD COLUMN region_name VARCHAR(255) DEFAULT NULL AFTER division_name,
    ADD COLUMN province_factor DECIMAL(28, 10) DEFAULT NULL AFTER region_name,
    ADD COLUMN region_factor DECIMAL(28, 10) DEFAULT NULL AFTER province_factor,
    ADD COLUMN national_factor DECIMAL(28, 10) DEFAULT NULL AFTER region_factor,
    ADD COLUMN non_fossil_excluded_factor DECIMAL(28, 10) DEFAULT NULL AFTER national_factor,
    ADD COLUMN national_fossil_power_factor DECIMAL(28, 10) DEFAULT NULL AFTER non_fossil_excluded_factor,
    ADD COLUMN row_no INT DEFAULT NULL AFTER national_fossil_power_factor,
    ADD COLUMN fuel_level1 VARCHAR(255) DEFAULT NULL AFTER row_no,
    ADD COLUMN fuel_level2 VARCHAR(255) DEFAULT NULL AFTER fuel_level1,
    ADD COLUMN fuel_level3 VARCHAR(255) DEFAULT NULL AFTER fuel_level2,
    ADD COLUMN fuel_level4 VARCHAR(255) DEFAULT NULL AFTER fuel_level3,
    ADD COLUMN lower_heat_value DECIMAL(28, 10) DEFAULT NULL AFTER fuel_level4,
    ADD COLUMN lower_heat_value_cv DECIMAL(18, 10) DEFAULT NULL AFTER lower_heat_value,
    ADD COLUMN co2_factor DECIMAL(28, 10) DEFAULT NULL AFTER lower_heat_value_cv,
    ADD COLUMN co2_factor_cv DECIMAL(18, 10) DEFAULT NULL AFTER co2_factor,
    ADD COLUMN gwp_value DECIMAL(28, 10) DEFAULT NULL AFTER co2_factor_cv,
    ADD COLUMN converted_factor DECIMAL(28, 10) DEFAULT NULL AFTER gwp_value,
    ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP AFTER create_time,
    ADD COLUMN remark VARCHAR(500) DEFAULT NULL AFTER update_time;

CREATE INDEX idx_cv_factor_record_table ON cv_factor_record (factor_table_code);
CREATE INDEX idx_cv_factor_record_sample_key ON cv_factor_record (factor_key);

ALTER TABLE cv_dimension_record
    ADD COLUMN field07 VARCHAR(255) DEFAULT NULL AFTER field06,
    ADD COLUMN field08 VARCHAR(255) DEFAULT NULL AFTER field07,
    ADD COLUMN field09 VARCHAR(255) DEFAULT NULL AFTER field08,
    ADD COLUMN field10 VARCHAR(255) DEFAULT NULL AFTER field09,
    ADD COLUMN field11 VARCHAR(255) DEFAULT NULL AFTER field10,
    ADD COLUMN field12 VARCHAR(255) DEFAULT NULL AFTER field11,
    ADD COLUMN field13 VARCHAR(255) DEFAULT NULL AFTER field12,
    ADD COLUMN field14 VARCHAR(255) DEFAULT NULL AFTER field13,
    ADD COLUMN field15 VARCHAR(255) DEFAULT NULL AFTER field14,
    ADD COLUMN field16 VARCHAR(255) DEFAULT NULL AFTER field15,
    ADD COLUMN field17 VARCHAR(255) DEFAULT NULL AFTER field16,
    ADD COLUMN field18 VARCHAR(255) DEFAULT NULL AFTER field17,
    ADD COLUMN field19 VARCHAR(255) DEFAULT NULL AFTER field18,
    ADD COLUMN field20 VARCHAR(255) DEFAULT NULL AFTER field19,
    ADD COLUMN field21 VARCHAR(255) DEFAULT NULL AFTER field20,
    ADD COLUMN field22 VARCHAR(255) DEFAULT NULL AFTER field21;
